version: "2"
services:

  stockmanagement:
    image: openlmis/stockmanagement:1.0.0-BETA-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-Dlogging.config=/logback.xml -Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  contract_tests:
    image: openlmis/dev:1
    env_file: .env
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    links:
    - db
    - log
    - nginx
    - consul
    - auth
    - referencedata
    - stockmanagement

    entrypoint:
      - 'gradle'
      - 'clean'
      - 'waitFor'
      - '-Pcontainers=
        ${BASE_URL}/auth
        ,${BASE_URL}/stockmanagement
        ,${BASE_URL}/referencedata'
      - 'cucumber'
      - '-Ptags=
      @StockCardTemplatesTests,
      @StockEventsTests,
      @StockCardsTests,
      @StockReasonsTests,
      @PhysicalInventoriesTests'

  referencedata:
    image: openlmis/referencedata:4.0.0-SNAPSHOT
    env_file: .env
    mem_limit: 512m
    environment:
      JAVA_OPTS: '-Xmx512m -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  auth:
    image: openlmis/auth:3.0.2-SNAPSHOT
    env_file: .env
    mem_limit: 512m
    environment:
      JAVA_OPTS: '-Xmx512m -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

volumes:
  gradlecache:
    external: false
