version: "2"
services:

  notification:
    image: openlmis/notification:${OL_NOTIFICATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  contract_tests:
    image: openlmis/dev:${DOCKER_DEV_IMAGE_VERSION}
    env_file: settings.env
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    links:
    - db
    - log
    - nginx
    - consul
    - auth
    - referencedata
    - notification

    entrypoint:
      - 'gradle'
      - 'clean'
      - 'waitFor'
      - '-Pcontainers=
        ${BASE_URL}/auth
        ,${BASE_URL}/notification
        ,${BASE_URL}/referencedata'
      - 'cucumber'
      - '-Ptags=@VerificationTests'
      - '--stacktrace'
      - '--no-daemon'

volumes:
  gradlecache:
    external: false
