version: "2"
services:

  stockmanagement:
    image: openlmis/stockmanagement:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      JAVA_OPTS: '-Dlogging.config=/logback.xml -Dflyway.locations=classpath:db/migration,filesystem:/demo-data'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  contract_tests:
    image: openlmis/dev:3
    env_file: .env
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    links:
    - db
    - log
    - nginx
    - consul
    - auth
    - referencedata
    - stockmanagement

    entrypoint:
      - 'gradle'
      - 'clean'
      - 'waitFor'
      - '-Pcontainers=
        ${BASE_URL}/auth
        ,${BASE_URL}/stockmanagement
        ,${BASE_URL}/referencedata'
      - 'cucumber'
      - '-Ptags=
      @StockCardTemplatesTests,
      @StockEventsTests,
      @StockCardsTests,
      @StockReasonsTests,
      @PhysicalInventoriesTests'

volumes:
  gradlecache:
    external: false
