version: "2"
services:

  stockmanagement:
    image: openlmis/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
      spring_profiles_active: demo-data,refresh-db
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  contract_tests:
    image: openlmis/dev:${DOCKER_DEV_IMAGE_VERSION}
    env_file: settings.env
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    links:
    - db
    - redis
    - log
    - nginx
    - consul
    - auth
    - referencedata
    - stockmanagement

    entrypoint:
      - 'gradle'
      - 'clean'
      - 'waitFor'
      - '-Pcontainers=
        ${BASE_URL}/auth
        ,${BASE_URL}/stockmanagement
        ,${BASE_URL}/referencedata'
      - 'cucumber'
      - '-Ptags=
      @StockCardTemplatesTests,
      @StockEventsTests,
      @StockCardsTests,
      @StockReasonsTests,
      @PhysicalInventoriesTests'
      - '--stacktrace'
      - '--no-daemon'

volumes:
  gradlecache:
    external: false
